language: node_js
node_js:
- '5'
cache:
  yarn: true
  directories:
  - node_modules
script:
- git clone --depth=10 https://github.com/dhis2/gis-api.git 
- cd gis-api
- npm install
- npm run build
- cd ..
- npm link
- npm run build
