language: node_js
node_js:
- '5'
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- cd $HOME
- git clone --depth=10 https://github.com/dhis2/gis-api.git
- cd gis-api
- npm install
- npm run build
script:
- npm link gis-api
- npm run build
